#!/usr/bin/env ruby

require "hermaeus"

if ARGV.length == 0 || ARGV[0].match(/^-{0,2}help$/) || ARGV[0] == "-h"
	Hermaeus.help
elsif ARGV[0].match(/^-{0,2}version$/) || ARGV[0] == "-v"
	puts Hermaeus::VERSION
elsif ARGV[0] == "seek"
	ARGV.shift
	if ARGV[0].nil?
		Hermaeus.help
	else
		Hermaeus.init
		Hermaeus.connect
		type = ARGV.shift
		if type == "com"
			raise ArgumentError, "com MUST have thread IDs specified" unless ARGV.length > 0
		end
		arc = Hermaeus::Archivist.new
		Hermaeus.seek(type, ARGV) do |post|
			apoc = Hermaeus::Apocryphon.new post
			Hermaeus.log.info apoc.to_s
			arc.save_to_file apoc
		end
	end
else
	Hermaeus.help
end
